const EUROPE_TOP_FIVE = ["en", "ru", "de", "fr", "it"];
const WORLD_TOP_FIVE = ["en", "zh", "hi", "es", "ar"];

export const PRESETS = {
    EUROPE_TOP_FIVE,
    EUROPE_TOP_TEN: [...EUROPE_TOP_FIVE, "es", "tr", "pl", "uk", "nl"],

    EUROPE_TOP_20: [
        ...EUROPE_TOP_FIVE, "es", "tr", "pl", "uk", "nl",
        "ro", "pt", "sv", "el", "hu", "cs", "bg", "sr", "da", "fi"
    ],

    WORLD_TOP_FIVE,
    WORLD_TOP_TEN: [...WORLD_TOP_FIVE, "fr", "bn", "pt", "ru", "id"],

    WORLD_TOP_20: [...WORLD_TOP_FIVE, "fr", "bn", "pt", "ru", "id",
        "ur",
        "de",
        "ja",
        "vi",
        "te",
        "tr",
        "ko",
        "it",
        "fa"
    ],
    All: [
        "zh", 
        "zh-cn",
        "zh-tw", 
        "zh-hk",
        "es", 
        "es-mx",
        "en", 
        "en-us", 
        "en-gb",
        "hi",
        "bn",
        "pt",
        "pt-br",
        "ru",
        "ur",
        "id",
        "de",
        "ja",
        "mr",
        "te",
        "ta",
        "tr",
        "ko",
        "fr",
        "vi",
        "pa",
        "it",
        "ha",
        "sw",
        "fa",
        "kn",
        "gu",
        "th",
        "pl",
        "uk",
        "my",
        "yo",
        "or",
        "az",
        "ml",
        "ro",
        "uz",
        "si",
        "hu",
        "so",
        "el",
        "cs",
        "zu",
        "sk",
        "be",
        "bg",
        "tl",
        "ph",
        "mg",
        "sr",
        "hr",
        "hy",
        "sq",
        "kk",
        "kn",
        "as",
        "ne",
        "lo",
        "km",
        "mn",
        "ky",
        "tg",
        "sv",
        "no",
        "da",
        "fi",
        "et",
        "lv",
        "lt",
        "sl",
        "bs",
        "mk",
        "xh",
        "ka",
        "ga"
    ]
};